import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "../styles/globals.css";
import { PackageProvider } from "./dashboard/components/PackageContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fraktal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scrollbar-hide">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased scrollbar-hide overflow-x-hidden`}
      >
        <header className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-backdrop-filter:bg-background/60">
          <div className="container mx-auto flex h-14 items-center justify-between px-4">
            {/* Logo */}
            <Link
              href="/"
              className="flex items-center space-x-2 text-xl font-bold text-foreground hover:text-primary transition-colors"
            >
              Fraktal
            </Link>

            {/* Navigation Links */}
            <nav className="flex items-center space-x-6">
              <Link
                href="/dashboard"
                className="text-sm font-medium text-muted-foreground hover:text-foreground transition-colors"
              >
                Dashboard
              </Link>
              <Link
                href="/messages"
                className="text-sm font-medium text-muted-foreground hover:text-foreground transition-colors"
              >
                Messages
              </Link>
              <Link
                href="/createPackage"
                className="text-sm font-medium text-muted-foreground hover:text-foreground transition-colors"
              >
                Create Package
              </Link>
              <Link
                href="/activePackage"
                className="text-sm font-medium text-muted-foreground hover:text-foreground transition-colors"
              >
                Active Packages
              </Link>
            </nav>
          </div>
        </header>
        <PackageProvider>
          <main className="flex-1">
            {children}
          </main>
        </PackageProvider>
      </body>
    </html>
  );
}
