#!/bin/bash

set -e

echo "Generating admin keys for each Convex backend..."
echo ""

# Generate and capture SENDER key
echo "=== SENDER Backend (port 3210) ==="
SENDER_OUTPUT=$(docker compose exec convex-sender ./generate_admin_key.sh 2>&1)
echo "$SENDER_OUTPUT"
SENDER_KEY=$(echo "$SENDER_OUTPUT" | grep -A 1 "Admin key:" | tail -n 1 | xargs)
echo ""

# Generate and capture TRANSPORTER key
echo "=== TRANSPORTER Backend (port 3220) ==="
TRANSPORTER_OUTPUT=$(docker compose exec convex-transporter ./generate_admin_key.sh 2>&1)
echo "$TRANSPORTER_OUTPUT"
TRANSPORTER_KEY=$(echo "$TRANSPORTER_OUTPUT" | grep -A 1 "Admin key:" | tail -n 1 | xargs)
echo ""

# Generate and capture RECEIVER key
echo "=== RECEIVER Backend (port 3230) ==="
RECEIVER_OUTPUT=$(docker compose exec convex-receiver ./generate_admin_key.sh 2>&1)
echo "$RECEIVER_OUTPUT"
RECEIVER_KEY=$(echo "$RECEIVER_OUTPUT" | grep -A 1 "Admin key:" | tail -n 1 | xargs)
echo ""

# Write to .env.convex file
ENV_FILE=".env.convex"
echo "Writing admin keys to $ENV_FILE..."
cat > "$ENV_FILE" << EOF
# Convex Admin Keys (generated by ./setup-convex.sh)
CONVEX_ADMIN_KEY_SENDER="$SENDER_KEY"
CONVEX_ADMIN_KEY_TRANSPORTER="$TRANSPORTER_KEY"
CONVEX_ADMIN_KEY_RECEIVER="$RECEIVER_KEY"
EOF

echo ""
echo "==================================="
echo "✓ Admin keys successfully saved to $ENV_FILE"
echo "==================================="
echo ""
echo "Keys generated:"
echo "CONVEX_ADMIN_KEY_SENDER=$SENDER_KEY"
echo "CONVEX_ADMIN_KEY_TRANSPORTER=$TRANSPORTER_KEY"
echo "CONVEX_ADMIN_KEY_RECEIVER=$RECEIVER_KEY"
echo "==================================="
